import { v4 as uuidv4 } from 'uuid';
import { type AnalysisResult } from '@oddslens/shared';
import { DISCLAIMER_TEXT } from '@oddslens/shared';

/**
 * MOCK=true 일 때 반환하는 데모 데이터
 * 실제 API 키 없이도 앱을 테스트할 수 있습니다
 */
export function getMockAnalysisResult(): AnalysisResult {
  const now = new Date().toISOString();
  const id = uuidv4();

  return {
    id,
    createdAt: now,
    isMock: true,
    disclaimer: DISCLAIMER_TEXT.main,
    processingTimeMs: 1234,
    matches: [
      {
        matchName: '맨체스터 시티 vs 아스날',
        homeTeam: '맨체스터 시티',
        awayTeam: '아스날',
        league: '잉글랜드 프리미어리그',
        matchDate: '2025-12-21',
        sport: '축구',
        overround: 0.052,
        options: [
          {
            label: '홈승 (맨체스터 시티)',
            odds: 1.85,
            impliedProbability: 0.541,
            fairProbability: 0.514,
            modelProbability: 0.52,
            ev: -0.038,
            confidence: 'high',
            reasoning: '[데모] 최근 5경기 3승 1무 1패. 홈 승률 67%. 아스날 대비 체력 우위 예상.',
            sources: ['Premier League Stats', 'BBC Sport'],
          },
          {
            label: '무승부',
            odds: 3.50,
            impliedProbability: 0.286,
            fairProbability: 0.272,
            modelProbability: 0.23,
            ev: -0.195,
            confidence: 'medium',
            reasoning: '[데모] 양 팀 모두 공격적 스타일. 무승부 가능성은 낮음.',
            sources: ['Opta Stats'],
          },
          {
            label: '원정승 (아스날)',
            odds: 4.20,
            impliedProbability: 0.238,
            fairProbability: 0.226,
            modelProbability: 0.25,
            ev: 0.05,
            confidence: 'medium',
            reasoning: '[데모] 아스날 원정 최근 4경기 2승. 가성비 좋은 픽 가능성.',
            sources: ['Arsenal Official', 'Transfermarkt'],
          },
        ],
        selectedPick: {
          label: '원정승 (아스날)',
          odds: 4.20,
          impliedProbability: 0.238,
          fairProbability: 0.226,
          modelProbability: 0.25,
          ev: 0.05,
          confidence: 'medium',
          reasoning: '[데모] 아스날 원정 최근 4경기 2승. EV 양수 픽.',
          sources: ['Arsenal Official'],
        },
      },
      {
        matchName: '레알 마드리드 vs 바르셀로나',
        homeTeam: '레알 마드리드',
        awayTeam: '바르셀로나',
        league: '스페인 라리가',
        matchDate: '2025-12-22',
        sport: '축구',
        overround: 0.048,
        options: [
          {
            label: '홈승 (레알 마드리드)',
            odds: 2.10,
            impliedProbability: 0.476,
            fairProbability: 0.454,
            modelProbability: 0.48,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] 엘 클라시코 최근 홈 레알 3연승. 음바페 폼 상승세.',
            sources: ['La Liga', 'ESPN'],
          },
          {
            label: '무승부',
            odds: 3.30,
            impliedProbability: 0.303,
            fairProbability: 0.289,
            modelProbability: 0.28,
            ev: -0.076,
            confidence: 'low',
            reasoning: '[데모] 두 팀 모두 무승부 의도가 낮음.',
            sources: [],
          },
          {
            label: '원정승 (바르셀로나)',
            odds: 3.60,
            impliedProbability: 0.278,
            fairProbability: 0.265,
            modelProbability: 0.24,
            ev: -0.136,
            confidence: 'medium',
            reasoning: '[데모] 바르셀로나 원정 엘클 최근 부진.',
            sources: ['Barcelona Official'],
          },
        ],
        selectedPick: {
          label: '홈승 (레알 마드리드)',
          odds: 2.10,
          impliedProbability: 0.476,
          fairProbability: 0.454,
          modelProbability: 0.48,
          ev: 0.008,
          confidence: 'high',
          reasoning: '[데모] 엘 클라시코 홈 레알 3연승. 양수 EV.',
          sources: ['La Liga'],
        },
      },
      {
        matchName: 'PSG vs 올랭피크 리옹',
        homeTeam: 'PSG',
        awayTeam: '올랭피크 리옹',
        league: '프랑스 리그 1',
        matchDate: '2025-12-22',
        sport: '축구',
        overround: 0.062,
        options: [
          {
            label: '홈승 (PSG)',
            odds: 1.55,
            impliedProbability: 0.645,
            fairProbability: 0.608,
            modelProbability: 0.65,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] PSG 홈 압도적 우위. 리옹 수비 불안정.',
            sources: ['Ligue 1', 'L\'Equipe'],
          },
          {
            label: '무승부',
            odds: 4.00,
            impliedProbability: 0.250,
            fairProbability: 0.236,
            modelProbability: 0.20,
            ev: -0.200,
            confidence: 'low',
            reasoning: '[데모] PSG 압도적 우위로 무승부 가능성 낮음.',
            sources: [],
          },
          {
            label: '원정승 (리옹)',
            odds: 6.50,
            impliedProbability: 0.154,
            fairProbability: 0.145,
            modelProbability: 0.15,
            ev: -0.025,
            confidence: 'low',
            reasoning: '[데모] 리옹 원정 PSG 전 승률 매우 낮음.',
            sources: [],
          },
        ],
        selectedPick: {
          label: '홈승 (PSG)',
          odds: 1.55,
          impliedProbability: 0.645,
          fairProbability: 0.608,
          modelProbability: 0.65,
          ev: 0.008,
          confidence: 'high',
          reasoning: '[데모] PSG 홈 우위. EV 양수.',
          sources: ['Ligue 1'],
        },
      },
    ],
    recommendations: [
      {
        type: 'stable',
        typeName: '안정형',
        picks: [
          {
            matchName: '레알 마드리드 vs 바르셀로나',
            homeTeam: '레알 마드리드',
            awayTeam: '바르셀로나',
            pick: '홈승 (레알 마드리드)',
            odds: 2.10,
            modelProbability: 0.48,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] 엘 클라시코 홈 레알 3연승.',
          },
          {
            matchName: 'PSG vs 올랭피크 리옹',
            homeTeam: 'PSG',
            awayTeam: '올랭피크 리옹',
            pick: '홈승 (PSG)',
            odds: 1.55,
            modelProbability: 0.65,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] PSG 홈 압도적 우위.',
          },
        ],
        combinedOdds: 3.255,
        combinedProbability: 0.312,
        combinedEV: 0.0163,
        riskLevel: 'low',
        riskScore: 22,
        summary: 'EV 양수 2경기 조합. 낮은 리스크, 안정적 접근.',
        disclaimer: DISCLAIMER_TEXT.main,
      },
      {
        type: 'balanced',
        typeName: '균형형',
        picks: [
          {
            matchName: '레알 마드리드 vs 바르셀로나',
            homeTeam: '레알 마드리드',
            awayTeam: '바르셀로나',
            pick: '홈승 (레알 마드리드)',
            odds: 2.10,
            modelProbability: 0.48,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] 엘 클라시코 홈 레알 3연승.',
          },
          {
            matchName: 'PSG vs 올랭피크 리옹',
            homeTeam: 'PSG',
            awayTeam: '올랭피크 리옹',
            pick: '홈승 (PSG)',
            odds: 1.55,
            modelProbability: 0.65,
            ev: 0.008,
            confidence: 'high',
            reasoning: '[데모] PSG 홈 압도적 우위.',
          },
          {
            matchName: '맨체스터 시티 vs 아스날',
            homeTeam: '맨체스터 시티',
            awayTeam: '아스날',
            pick: '원정승 (아스날)',
            odds: 4.20,
            modelProbability: 0.25,
            ev: 0.05,
            confidence: 'medium',
            reasoning: '[데모] 아스날 원정 최근 부활.',
          },
        ],
        combinedOdds: 13.67,
        combinedProbability: 0.0780,
        combinedEV: 0.066,
        riskLevel: 'medium',
        riskScore: 48,
        summary: '3경기 균형 조합. EV와 배당의 균형점.',
        disclaimer: DISCLAIMER_TEXT.main,
      },
      {
        type: 'aggressive',
        typeName: '공격형',
        picks: [
          {
            matchName: '맨체스터 시티 vs 아스날',
            homeTeam: '맨체스터 시티',
            awayTeam: '아스날',
            pick: '원정승 (아스날)',
            odds: 4.20,
            modelProbability: 0.25,
            ev: 0.05,
            confidence: 'medium',
            reasoning: '[데모] 아스날 원정 부활 조짐.',
          },
          {
            matchName: '레알 마드리드 vs 바르셀로나',
            homeTeam: '레알 마드리드',
            awayTeam: '바르셀로나',
            pick: '원정승 (바르셀로나)',
            odds: 3.60,
            modelProbability: 0.24,
            ev: -0.136,
            confidence: 'medium',
            reasoning: '[데모] 고배당 역전 시나리오.',
          },
          {
            matchName: 'PSG vs 올랭피크 리옹',
            homeTeam: 'PSG',
            awayTeam: '올랭피크 리옹',
            pick: '원정승 (리옹)',
            odds: 6.50,
            modelProbability: 0.15,
            ev: -0.025,
            confidence: 'low',
            reasoning: '[데모] 고위험 고배당 역전 픽.',
          },
        ],
        combinedOdds: 98.28,
        combinedProbability: 0.009,
        combinedEV: -0.115,
        riskLevel: 'high',
        riskScore: 85,
        summary: '고배당 공격형 조합. 매우 높은 리스크. 신중한 판단 필요.',
        disclaimer: DISCLAIMER_TEXT.main,
      },
    ],
  };
}
